### ISSUE TITLE
--filesystem=home

### ISSUE THREAD

**Issue by Anonim19992** [kennylevinsen/cura-flatpak#1]
It is advisable to add --filesystem = home to lines 8-11, otherwise it will not give access to the home directory, which will give its "-" to usability. I think few people will go to the folder with sudo rights every time.

`  "finish-args": [
        "--share=network",
        "--socket=wayland",
        "--socket=x11",
        "--device=dri"
        "--filesystem=home"
    ],`

**Comment by kennylevinsen** [comment]
Does giving home access result in Cura placing its config folder there on fresh installs? If so, then that's too much access.

I'm not at my home machine right now, but the current setup at least gives access to some home folders, such as downloads.

I have no idea what you mean by "with sudo rights". Cura doesn't `sudo`.

**Comment by Anonim19992** [comment]
without this access, Cura did not see my home directory (only /). More precisely, in the home directory she saw only fontconfig with cache files.

**Comment by Anonim19992** [comment]
therefore, in the first few minutes (it was urgent to print the project, but gcode wasn’t ready), I had to resort to sudo to save the stl file in the var folder.

**Comment by kennylevinsen** [comment]
Weird, I usually have my STLs in my download folder (I do CAD on another machine), which worked fine.

I might look into it, but it depends on being able to avoid Cura writing anything to $HOME outside of saving files, which would be a no-go for me. `--filesystem=home` is technically a hack for applications that are not correctly using an xdg-portal for file access, and undermines a big part of sandboxing.

**Comment by Anonim19992** [comment]
For details, I recorded a video of the entire action. 4.3 and 4.2 - there is no difference.
youtube watch?v=b5xZ_PvW1OQ
"Weird, I usually have my STLs in my download folder (I do CAD on another machine), which worked fine."
--filesystem=xdg-download ?
or as an option, register mkdir in the script and make a hard link to this folder via --filesystem =?

**Comment by kennylevinsen** [comment]
I found that Cura doesn't seem to litter $HOME when it is enabled, so I fixed it in master. Also bumped to 4.3.0 while I was at it.

To be honest, I had already done this locally ages ago, but had *entirely* forgotten about it and apparently hadn't committed and pushed. I'll try to remember to keep this repo up to date. :)
