### ISSUE TITLE
Publish on FlatHub

### ISSUE THREAD

**Issue by xarbit** [kennylevinsen/cura-flatpak#2]
Hi, i was looking for a cura based flatpak for usage on Fedora Silverlight. 
Why don't you contribute your cura flatpak to the flathub repo and make it easily accessible? 

https://github.com/flathub/flathub/blob/master/CONTRIBUTING.md

**Comment by Anonim19992** [comment]
The company itself has refused this distribution of its package in favor of appimage

**Comment by xarbit** [comment]
I know that they refuse to support it on their own, they do not refuse community support.

**Comment by kennylevinsen** [comment]
Why did you close this issue? I'm not opposed to publishing it there.

**Comment by mmstick** [comment]
Any plans to publish this? Would be great to have a recent version of Cura in Pop / Ubuntu 20.04

**Comment by xarbit** [comment]
@mmstick @kennylevinsen I plan to create Cura as Flatpak without using the AppImage. I did this for PrusaSlicer already.

**Comment by kennylevinsen** [comment]
Ah, perfect - using the AppImage is indeed a hack.
